### ISSUE TITLE
[Style] 배포(prod) 환경에서 글자가 잘 안보이는 현상

### ISSUE THREAD

**Issue by blingblin-g** [42-world/42world-Frontend-Mobile#116]
![image](https://user-images.githubusercontent.com/60090391/151688248-b1e0d5c5-fc45-4d8a-85fa-2f50eea909f9.png)
글자색 때문에 잘 안보입니다.

**Comment by hyongti** [comment]
아 이거 제가 수정하다가 props 하나 빼먹어서 이렇게 됐었는데 피그마대로 검은 배경으로 바꿨슴다

이슈 닫을게용
