### ISSUE TITLE
[Feature] 게시판 간의 스위칭

### ISSUE THREAD

**Issue by GulSam00** [42-world/42world-Frontend-Mobile#196]
## 작업할 내용
게시판을 클릭하면 다른 게시판을 이동할 수 있게 게시판 목록이 내려오게끔 기능 추가.
글 작성 시 로직(createArticle  컴포넌트)을 참고.

## 해야할 일
- [ ] 게시판 스위칭 기능 추가.

**Comment by chichoon** [comment]
- [x] 카테고리 페이지에 게시판 선택 바 추가
- [x] 카테고리 선택하면 링크 이동
- [x] 링크 이동 후 컴포넌트 리로드
- [x] 스타일 적용

**Comment by chichoon** [comment]
PR #199
