### ISSUE TITLE
[Feature] 404페이지 캐릭터와 로고 수정

### ISSUE THREAD

**Issue by euiminnn** [42-world/42world-Frontend-Mobile#228]
## 작업할 내용

캐릭터와 로고가 바뀌었는데 404페이지에 적용이 안되었습니다.
<img width="391" alt="image" src="https://user-images.githubusercontent.com/39411711/158064781-44d8a434-8388-46bf-a919-7315cb74fe7a.png">

**Comment by chichoon** [comment]
수정후 머지되었으므로 이슈 닫을게용가리자몽키스패너
