### ISSUE TITLE
[Bug] 인증완료 버튼 말고 일반 커서로

### ISSUE THREAD

**Issue by euiminnn** [42-world/42world-Frontend-Mobile#232]
## 오류 사진 및 설명
<img width="334" alt="image" src="https://user-images.githubusercontent.com/39411711/158353044-c0cc4d68-ce51-4e72-a815-7caa188e0af0.png">

인증 전에만 버튼이고 인증 후 '인증완료' 되었을 땐 버튼 대신 일반 커서가 뜨면 좋을 것 같습니다.

저번에 한 번 말씀드렸던 것 같은데 많이 어려운 부분일까요?

**Comment by Skyrich2000** [comment]
출시 직전에 제가 급하게 수정부분이라서... 프론트 분들이 손대시면 금방 해결하실거같습니다.

**Comment by chichoon** [comment]
이부분 한번볼게용
