### ISSUE TITLE
[Bug] 컴포넌트 겹침

### ISSUE THREAD

**Issue by euiminnn** [42-world/42world-Frontend-Mobile#236]
## 오류 사진 및 설명
![B86315BD-3460-4574-9D37-CF0AC1F1EAEE](https://user-images.githubusercontent.com/39411711/158488403-7e200c54-5ed5-44d2-85cf-637c6c9df43d.jpeg)

![C4FCDA93-F063-4826-B299-FD9F9BDF6FD7](https://user-images.githubusercontent.com/39411711/158488411-4a1a5ebf-60b0-4cb7-ac96-b07646893336.jpeg)

## 발생 위치
글 작성하기 페이지

**Comment by chichoon** [comment]
#239 머지되었습니당
