### ISSUE TITLE
[Bug] 글쓰기 버튼 눌렀을 때 커서가 자동으로 '내용'으로 감

### ISSUE THREAD

**Issue by euiminnn** [42-world/42world-Frontend-Mobile#237]
## 오류 사진 및 설명
<img width="424" alt="image" src="https://user-images.githubusercontent.com/39411711/158952955-75ff2435-d51f-4578-b7cf-d3dbdc6eaba4.png">

커서의 첫 위치는 '내용'이 아니라 '제목'으로 가면 더 좋을 것 같습니다

**Comment by chichoon** [comment]
#238 머지되었습니당
