### ISSUE TITLE
댓글 쓰면 state 변경이 자동으로 이루어지지 않음

### ISSUE THREAD

**Issue by PIut0** [42-world/42world-Frontend-Mobile#55]
댓글 썼을때 페이지 새로고침이나 re-rendering 이 이루어지지 않아서
댓글작성 handle 함수에 댓글 작성 후 댓글을 새로 불러오는 부분이 추가되어야 할것 같습니다!

**Comment by PIut0** [comment]
@hyongti

**Comment by rkskekzzz** [comment]
이거 백엔드에서 writer 와 comment 테이블 join 하지 않고 넘기고 있어서 생기는 에러 때문에 잠시 주석되어있습니다

**Comment by blingblin-g** [comment]
해결되었습니다
